### ISSUE TITLE
Fix OverwriteModelError on `sevr start`

### ISSUE THREAD

**Issue by bpowers1215** [ExclamationLabs/sevr-cli#2]
OverwriteModelError occurring on `sevr start`

```
OverwriteModelError: Cannot overwrite `metadata` model once compiled.
    at NativeConnection.Connection.model (/Users/brandon/projects/sevr/sevr/node_modules/mongoose/lib/connection.js:727:13)
    at Object.exports.createModel (/Users/brandon/projects/sevr/sevr/lib/meta.js:8:17)
    at connect.then (/Users/brandon/projects/sevr/sevr/index.js:214:10)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by bpowers1215** [comment]
This occurred due to Sevr starting twice and so attempting to create a duplicate metadata model.  A second start was triggered by a call to `sevr.start()` in the sevr-tutorial index.js
